// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu3Mc1Pd0Mji817f_UzTB_iG65oPYINzE',
    appId: '1:712970756898:web:e7693d332b24135c7afb7b',
    messagingSenderId: '712970756898',
    projectId: 'explorexpert-68106',
    authDomain: 'explorexpert-68106.firebaseapp.com',
    storageBucket: 'explorexpert-68106.appspot.com',
    measurementId: 'G-3B2HQB2WGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzxKEslGHDrL9Xx1b5e1hr7b62uBhPd-8',
    appId: '1:712970756898:android:60844d23253405f47afb7b',
    messagingSenderId: '712970756898',
    projectId: 'explorexpert-68106',
    storageBucket: 'explorexpert-68106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkkcUTmlcZKARNhpi_AP3B6ndH2K_BfDs',
    appId: '1:712970756898:ios:54981387218ac5bd7afb7b',
    messagingSenderId: '712970756898',
    projectId: 'explorexpert-68106',
    storageBucket: 'explorexpert-68106.appspot.com',
    androidClientId: '712970756898-uk0j1b6o7koo1jq7a02ui3588j6q945q.apps.googleusercontent.com',
    iosClientId: '712970756898-jd3mge8m7m6jkt3spej7r5c2uah1mfbn.apps.googleusercontent.com',
    iosBundleId: 'com.example.explorexpert',
  );
}
